database:
  dbms: 'postgresql'
  host: '35.235.95.37' # Replace with your DB host
  port: 5439 # Replace with your DB port
  user: 'jize' # Replace with your DB username
  password: 'jz@uscdash23'# Replace with your DB password


mapping:
  columns:
    user_id: 'user_id'
    timestamp: 'timestamp'
    value: 'value'
  tables:
    user_table:
      name: 'geomts_users'
      columns:
        user_id: String(50)
        device: String(50)
        location: String(50)
    time_series:
      - heart_rates
      - calories
      - mets
      - distances
      - steps
      - sleep
      - weight
    geo:
      - locations
