version: "1.0"
services:
  dashboard:
    build:
        context: .
    container_name: dashboard
    ports:
      - 8501:8501
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"