name: Pull API code, Build and push the docker image to DockerHub

on:
  push:
    branches:
      - main
      - jize

jobs:
  push_to_registry:
    name: Push the docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Fetch code from Repository API
        uses: actions/checkout@v3
        with:
          repository: 'USC-InfoLab/w4h-api'
          path: '.'
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: uscimsc/w4h:latest
